{% set name = "edgetest-hub" %}
{% set version = "2023.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2765f27f52b4e812016982bef85ccd9283dbe9cecabe7869baec7cc77058357c

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install -vv --no-deps .

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - edgetest >=2021.12.3
    - git
    - hub
    - python >=3.8

test:
  imports:
    - edgetest_hub.plugin

about:
  home: https://github.com/capitalone/edgetest-hub
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: edgetest-hub is a hub plugin for edgetest
  description: |
    This plugin allows users to create virtual environments using conda instead of venv when using edgetest
  doc_url: https://capitalone.github.io/edgetest-hub
  dev_url: https://github.com/capitalone/edgetest-hub

extra:
  recipe-maintainers:
    - jdawang
    - gladysteh99
    - NikhilJArora
    - fdosani
    - ak-gupta
